{ This file was automatically created by Lazarus. Do not edit!
  This source is only used to compile and install the package.
 }

unit SimpleGameEngine2;

{$warn 5023 off : no warning about unused units}
interface

uses
  GDIPAPI, GDIPOBJ, GDIPUTIL, OpenAL, dglOpenGL, sgeErrorManager, 
  sgeCorePointerList, sgeResourceList, sgeWindow, SimpleGameEngine, 
  sgeCriticalSection, sgeDateUtils, sgeErrors, sgeFile, sgeFileUtils, sgeKeys, 
  sgeMemoryStream, sgeMetaInfoList, sgeOSPlatform, sgeSimpleCommand, 
  sgeSimpleContainer, sgeSimpleParameters, sgeStartParameters, sgeStringList, 
  sgeMathUtils, sgeSystemEvent, sgeSystemUtils, sgeThread, sgeTypes, 
  sgeControllerList, sgeEventControllers, sgeEventTimeEvent, sgeEventList, 
  sgeEventManager, sgeEventSubscriber, sgeEventSubscriberGroupList, 
  sgeEventSubscriberList, sgeEventWindow, sgeExtensionControllers, 
  sgeExtensionFileSystem, sgeExtensionGraphic, sgeExtensionList, 
  sgeExtensionGUI, sgeExtensionResourceList, sgeExtensionShell, 
  sgeExtensionSound, sgeExtensionStartParameters, sgeExtensionVariables, 
  sgeExtensionWindow, sgeGraphicColor, sgePackFileList, sgePackFileReader, 
  sgePackFileWriter, sgeSoundBuffer, sgeSoundBufferLoader, 
  sgeSoundBufferWavLoader, sgeSoundSource, sgeTemplateCollection, 
  sgeTemplateThreadSafeList, sgeSystemCursor, sgeSystemIcon, 
  sgeSystemTimeEvent, sgeSystemTrayIcon, sgeVariableBooleanNormal, 
  sgeVariableBooleanBase, sgeVariableBooleanProc, sgeVariableIntegerNormal, 
  sgeVariableIntegerBase, sgeVariableIntegerProc, sgeVariableList, 
  sgeVariableSingleNormal, sgeVariableSingleBase, sgeVariableSingleProc, 
  sgeVariableColorNormal, sgeVariableColorBase, sgeVariableColorProc, 
  sgeTemplateThreadSafeCollection, sgeShellCommand_System_Read, 
  sgeShellCommand, sgeShellCommandList, sgeCommandHistory, sgeSystemConsole, 
  sgeExtensionKeyCommand, sgeShellCommandQueue, sgeKeyCommandKeyboard, 
  sgeKeyCommandMouse, sgeKeyCommandJoystick, sgeKeyCommandJoystickButtonInfo, 
  sgeKeyCommandJoystickInfo, sgeKeyCommandJoystickAxisInfo, 
  sgeKeyCommandTypes, sgeKeyCommandJoystickPadInfo, 
  sgeKeyCommandJoystickAxisInfoTilt, sgeShellCommandParameterBase, 
  sgeShellCommandParameterString, sgeShellCommandParameterList, 
  sgeShellCommandParameterEnum, sgeShellCommandParameterFloat, 
  sgeShellCommand_System_ReadLn, sgeShellCommands, 
  sgeShellCommand_System_ReadKey, sgeShellCommand_Variable_Clear, 
  sgeShellCommand_Dialog_Message, sgeShellCommand_Variable_Delete, 
  sgeShellCommand_Variable_Set, sgeShellCommand_System_Sleep, sgeShellLine, 
  sgeShellLineItem, sgeShellLineList, sgeShellCommand_System_Write, 
  sgeShellCommand_System_Screenshot, sgeShellCommand_System_Label, 
  sgeStringUtils, sgeVariableEnumBase, sgeVariableEnumNormal, 
  sgeVariableStringProc, sgeVariables, sgeShellScript, sgeShellScriptList, 
  sgeShellCallStack, sgeShellCallStackItem, sgeShellCommand_System_Exit, 
  sgeShellCommand_System_Procedure, sgeShellCommand_System_Return, 
  sgeShellCommand_System_Execute, sgeShellCommand_System_Goto, 
  sgeShellCommand_System_Run, sgeShellCommandsUtils, 
  sgeShellCommand_System_Call, sgeShellCommand_Script_Clear, 
  sgeExtensionTimeEvent, sgeShellCommand_Script_Delete, 
  sgeShellCommand_Music_Random, sgeTimeEventList, sgeEventMusicPlayer, 
  sgeEventKeyboard, sgeEventMouse, sgeSystemFont, sgeJournal, 
  sgeExtensionMusicPlayer, sgeExtensionPackList, sgeMusicPlayerTrackList, 
  sgeSystemGlobalAtom, sgeMusicPlayerTaskBase, sgeMusicPlayerTaskList, 
  sgeTemplateList, sgeMusicPlayerTaskPlay, sgeMusicPlayerTaskStop, 
  sgeMusicPlayerTaskVolume, sgeVariableBooleanClass, sgeVariableColorClass, 
  sgeVariableEnumProc, sgeVariableIntegerClass, sgeVariableSingleClass, 
  sgeVariableStringBase, sgeVariableStringClass, sgeVariableStringNormal, 
  sgeVariableEnumClass, sgeEventGraphic, sgeShellCommand_Music_Next, 
  sgeShellCommand_Music_Play, sgeShellCommand_Music_Prev, 
  sgeShellCommand_CommandHistory_Load, sgeShellCommand_Command_List, 
  sgeCursor, sgeExtensionCursor, sgeShellCommand_CommandHistory_Clear, 
  sgeShellCommand_CommandHistory_Save, sgeShellCommand_Music_Stop, 
  sgeShellCommand_Script_Load, sgeKeyCommandMouseAction, 
  sgeKeyCommandMouseActionList, sgeKeyCommandKeyboardAction, 
  sgeKeyCommandKeyboardActionList, sgeWindowsVersion, sgeMatch, sgeMatchMask, 
  sgeShellCommand_System_Stop, sgeCorePointerUtils, sgeExtensionScenes, 
  sgeSceneBase, sgeSceneList, sgeViewBox, sgeGraphicColorUtils, sgeAnimation, 
  sgeAnimationFrame, sgeAnimationFrameList, sgeSprite, sgeSpriteLoader, 
  sgeSpriteLoaderGDIP, sgeDisplayElementAnimationUnmanaged, 
  sgeDisplayElementAnsiText, sgeDisplayElementFrame, sgeDisplayElementRect, 
  sgeDisplayElementSprite, sgeDisplayElementSpriteNine, 
  sgeDisplayElementSpritePart, sgeDisplayElementSpriteTile, 
  sgeGraphicOpenGLBuffer, sgeGraphicOpenGLCoordBuffer, sgeGraphicOpenGLShader, 
  sgeGraphicOpenGLShaderProgram, sgeGraphicOpenGLShaderProgramTable, 
  sgeGraphicOpenGLSprite, sgeGraphicOpenGLDrawObjectTable, 
  sgeGraphicOpenGLTypes, sgeGraphicOpenGLUtils, 
  sgeGraphicOpenGLVertexArrayObject, 
  sgeGraphicOpenGLDrawObjectAnimationUnamnaged, 
  sgeGraphicOpenGLDrawObjectAnsiText, sgeGraphicOpenGLDrawObjectFrame, 
  sgeGraphicOpenGLDrawObjectRect, sgeGraphicOpenGLDrawObjectSprite, 
  sgeGraphicOpenGLDrawObjectSpriteNine, sgeGraphicOpenGLDrawObjectSpritePart, 
  sgeGraphicOpenGLDrawObjectSpriteTile, sgeGraphicOpenGLDrawObjectFadeItem, 
  sgeGraphicOpenGLDrawObjectFadeItemList, sgeGraphicOpenGLLayer, 
  sgeAnsiFontGlyph, sgeResourceItem, sgeDisplayLayer;

implementation

end.
