{ This file was automatically created by Lazarus. Do not edit!
  This source is only used to compile and install the package.
 }

unit SimpleGameEngine2;

{$warn 5023 off : no warning about unused units}
interface

uses
  SimpleGameEngine, sgeCorePointerList, sgeCorePointerUtils, sgeCounter, 
  sgeCriticalSection, sgeDateUtils, sgeErrors, sgeFile, sgeFileUtils, 
  sgeJournal, sgeKeys, sgeMatch, sgeMatchMask, sgeMathUtils, sgeMemoryStream, 
  sgeOSPlatform, sgeSimpleCommand, sgeSimpleContainer, sgeSimpleParameters, 
  sgeStringList, sgeStringUtils, sgeSystemConsole, sgeSystemCursor, 
  sgeSystemEvent, sgeSystemFont, sgeSystemGlobalAtom, sgeSystemIcon, 
  sgeSystemTimeEvent, sgeSystemTrayIcon, sgeSystemUtils, sgeThread, sgeTypes, 
  sgeUniqueID, sgeViewBox, sgeWindowsVersion, sgeEventManager, 
  sgeEventSubscriber, sgeEventSubscriberGroupList, sgeEventSubscriberList, 
  sgeExtensionList, sgeControllerList, sgeExtensionControllers, 
  sgeExtensionCursor, sgeColorUtils, sgeExtensionGraphic, 
  sgeDisplayElementAnimation, sgeDisplayElementAnimationUnmanaged, 
  sgeDisplayElementAnsiText, sgeDisplayElementFrame, sgeDisplayElementRect, 
  sgeDisplayElementSprite, sgeDisplayElementSpriteNine, 
  sgeDisplayElementSpritePart, sgeDisplayElementSpriteTile, sgeDisplayLayer, 
  sgeAnimationFrame, sgeAnimationFrameList, sgeAnsiFontGlyph, sgeSpriteLoader, 
  sgeSpriteLoaderGDIP, sgeSpriteSaver, sgeSpriteSaverBmp, 
  sgeGraphicOpenGLBuffer, sgeGraphicOpenGLDrawObjectList, 
  sgeGraphicOpenGLDrawObjectTable, sgeGraphicOpenGLLayer, 
  sgeGraphicOpenGLLayerList, sgeGraphicOpenGLLayerTable, 
  sgeGraphicOpenGLShader, sgeGraphicOpenGLShaderProgram, 
  sgeGraphicOpenGLShaderProgramTable, sgeGraphicOpenGLSprite, 
  sgeGraphicOpenGLSpriteTable, sgeGraphicOpenGLTypes, sgeGraphicOpenGLUtils, 
  sgeGraphicOpenGLVertexArrayObject, sgeGraphicOpenGLDrawObjectAnimation, 
  sgeGraphicOpenGLDrawObjectAnimationUnamnaged, 
  sgeGraphicOpenGLDrawObjectAnsiText, sgeGraphicOpenGLDrawObjectFrame, 
  sgeGraphicOpenGLDrawObjectRect, sgeGraphicOpenGLDrawObjectSprite, 
  sgeGraphicOpenGLDrawObjectSpriteNine, sgeGraphicOpenGLDrawObjectSpritePart, 
  sgeGraphicOpenGLDrawObjectSpriteTile, sgeGraphicOpenGLDrawObjectFadeItem, 
  sgeGraphicOpenGLDrawObjectFadeItemList, sgeGUIElement, sgeGUIForm, 
  sgeGUIFormList, sgeGUIRect, sgeGUISprite, sgeGUISpriteButton, 
  sgeGUISpriteScrollbar, sgeGUIToggleSpriteButton, sgeGUIPropertyConstrains, 
  sgeGUIPropertyFloatPoint, sgeGUIPropertyScale, sgeGUIPropertySprite, 
  sgeKeyCommandTypes, sgeKeyCommandJoystickAxisInfo, 
  sgeKeyCommandJoystickAxisInfoTilt, sgeKeyCommandJoystickButtonInfo, 
  sgeKeyCommandJoystickInfo, sgeKeyCommandJoystickPadInfo, 
  sgeKeyCommandKeyboardAction, sgeKeyCommandKeyboardActionList, 
  sgeKeyCommandMouseAction, sgeKeyCommandMouseActionList, 
  sgeMusicPlayerTaskList, sgeMusicPlayerTrack, sgeMusicPlayerTrackList, 
  sgeMusicPlayerTaskPlay, sgeMusicPlayerTaskStop, sgeMusicPlayerTaskVolume, 
  sgePackFile, sgePackFileList, sgePackFileReader, sgePackFileWriter, 
  sgeMetaInfoList, sgeResourceItem, sgeResourceList, sgeSceneBase, 
  sgeSceneList, sgeExtensionShell, sgeLineEditor, sgeShellCallStack, 
  sgeShellCallStackItem, sgeShellCommandList, sgeShellCommandQueue, 
  sgeShellCommands, sgeShellLine, sgeShellLineItem, sgeShellLineList, 
  sgeShellScript, sgeShellScriptList, sgeShellCommandParameterEnum, 
  sgeShellCommandParameterFloat, sgeShellCommandParameterInteger, 
  sgeShellCommandParameterList, sgeShellCommandParameterString, 
  sgeShellCommand_Command_List, sgeShellCommand_CommandHistory_Clear, 
  sgeShellCommand_CommandHistory_Load, sgeShellCommand_CommandHistory_Save, 
  sgeShellCommand_Dialog_Message, sgeShellCommand_Music_Next, 
  sgeShellCommand_Music_Play, sgeShellCommand_Music_Prev, 
  sgeShellCommand_Music_Random, sgeShellCommand_Music_Stop, 
  sgeShellCommand_Script_Clear, sgeShellCommand_Script_Delete, 
  sgeShellCommand_Script_Load, sgeShellCommand_System_Call, 
  sgeShellCommand_System_Execute, sgeShellCommand_System_Exit, 
  sgeShellCommand_System_Goto, sgeShellCommand_System_Label, 
  sgeShellCommand_System_Procedure, sgeShellCommand_System_Read, 
  sgeShellCommand_System_ReadKey, sgeShellCommand_System_ReadLn, 
  sgeShellCommand_System_Return, sgeShellCommand_System_Run, 
  sgeShellCommand_System_Screenshot, sgeShellCommand_System_Sleep, 
  sgeShellCommand_System_Stop, sgeShellCommand_System_Write, 
  sgeShellCommand_Variable_Clear, sgeShellCommand_Variable_Delete, 
  sgeShellCommand_Variable_Set, sgeShellCommandsUtils, sgeSound, 
  sgeSoundSource, sgeSoundBufferLoader, sgeSoundBufferWavLoader, 
  sgeStartParameters, sgeTimeEventItem, sgeTimeEventList, sgeVariableBase, 
  sgeVariableList, sgeVariables, sgeVariableBooleanClass, 
  sgeVariableBooleanNormal, sgeVariableBooleanProc, sgeVariableColorClass, 
  sgeVariableColorNormal, sgeVariableColorProc, sgeVariableEnumClass, 
  sgeVariableEnumNormal, sgeVariableEnumProc, sgeVariableIntegerClass, 
  sgeVariableIntegerNormal, sgeVariableIntegerProc, sgeVariableSingleClass, 
  sgeVariableSingleNormal, sgeVariableSingleProc, sgeVariableStringClass, 
  sgeVariableStringNormal, sgeVariableStringProc, sgeWindow, GDIPAPI, GDIPOBJ, 
  GDIPUTIL, OpenAL, dglOpenGL, sgeGUILabel, sgeEventWindowSize, 
  sgeEventWindowMaximize, sgeEventWindowMinimize, sgeEventWindowRestore, 
  sgeEventWindowClose, sgeEventWindowSetFocus, sgeEventWindowLostFocus, 
  sgeEventWindowShow, sgeEventWindowHide, sgeEventWindowActivate, 
  sgeEventWindowDeactivate, sgeEventKeyboardChar, sgeEventKeyboardKeyUp, 
  sgeEventMouse, sgeEventMouseDown, sgeEventMouseDoubleClick, sgeEventMouseUp, 
  sgeEventMouseEnter, sgeEventMouseScroll, sgeEventMouseMove, 
  sgeEventMouseLeave, sgeEventGraphicShaderAdd, sgeEventGraphicFade, 
  sgeEventGraphicFadeAdd, sgeEventGraphicLayer, sgeEventGraphicLayerAdd, 
  sgeEventGraphicLayerDelete, sgeEventGraphicLayerUpdate, 
  sgeEventGraphicElement, sgeEventGraphicElementDelete, 
  sgeEventGraphicElementVisible, sgeEventGraphicElementClipRect, 
  sgeEventGraphicElementUpdate, sgeEventGraphicElementAdd, sgeEventController, 
  sgeEventControllerAttach, sgeEventControllerButtonUp, 
  sgeEventControllerDetach, sgeEventControllerButtonDown, 
  sgeEventControllerPovUp, sgeEventControllerPovDown, 
  sgeEventControllerAxisUp, sgeEventControllerAxisDown, 
  sgeEventControllerAxisValue, sgeEventTime, sgeEventMusicPlayer, 
  sgeEventMusicPlayerStart, sgeEventMusicPlayerStop, sgeDisplayElementTileSet;

implementation

end.
